### ISSUE TITLE
Question: Is there a way to disable past dates?

### ISSUE THREAD

**Issue by petergombos** [pushtell/react-bootstrap-date-picker#110]
How could I disable past day selection?

Awesome plugin! by the way. 
Thanks!

**Comment by gReis89** [comment]
You can control selectable dates with `minDate` and `maxDate` options:

> minDate - ISO date string to set the lowest allowable date value.
Optional
Type: string
Example: "2016-05-19T12:00:00.000Z"
maxDate - ISO date string to set the highest allowable date value.
Optional
Type: string
Example: "2016-05-19T12:00:00.000Z"

**Comment by petergombos** [comment]
Thank! Sorry, I cant believe I missed that! I'm closing this.
