### ISSUE TITLE
React 15.5 Deprecation Warnings Appearing Due to React-Bootstrap-Date-Picker import.

### ISSUE THREAD

**Issue by jronSomers** [pushtell/react-bootstrap-date-picker#114]
On application load, my bundle shoots out a warning about using both React.PropTypes and React.createClass. I traced it back to an import on one of my pages that use this very nice date picker component. The component eventually uses the "Portal" component which is the actual culprit that uses React.createClass.

I was wondering when this is going to get updated to get rid of these deprecation issues.

Thanks,

Jaron

* Version used:
* Browser Name and version: Chrome 57.0.2987.133
* Operating System and version (desktop or mobile): Win 7
![deprecationscreenshot](https://cloud.githubusercontent.com/assets/9777005/25238240/df1917fe-25ba-11e7-86cf-1b691036e5b1.PNG)

**Comment by wehriam** [comment]
This is a community supported project, PRs are very much appreciated!

**Comment by gengjiawen** [comment]
@wehriam There is a pr to fix this, can you merge it ?
