### ISSUE TITLE
Warning: "hasFeedback" property of "FormGroup" has been deprecated.

### ISSUE THREAD

**Issue by jwamsterdam** [pushtell/react-bootstrap-date-picker#12]
Is it corrent that I get the following error message in my console log: 

Warning: `<Input>` is deprecated. Use `<FormControl>`, `<Checkbox>`, or `<Radio>`, with `<FormGroup>` and/or `<InputGroup>` as needed instead.
Warning: "hasFeedback" property of "FormGroup" has been deprecated.
Use a `<FormControl.Feedback>` element.

And can you tell me how to fix it? Thank you!

**Comment by StefanoGitHub** [comment]
Me too.
I'm using: ```"react": "^15.0.2", "react-bootstrap": "^0.29.4", "react-dom": "^15.0.2"```
Thanks

**Comment by wehriam** [comment]
Working on a new release now, but have run into an issue with Firefox. I'll keep you updated.

**Comment by wehriam** [comment]
[Release 3.0.0](https://www.npmjs.com/package/react-bootstrap-date-picker) is out and uses `<InputGroup>`, which should resolve this issue.
