### ISSUE TITLE
WARNINGS: React.createClass is deprecated, accessing PropTypes via the React main package is deprecated

### ISSUE THREAD

**Issue by flygis** [pushtell/react-bootstrap-date-picker#127]
I installed react-bootstrap-date-picker, and used it in a component, and I got some deprecated errors.

## Expected Behavior

react-bootstrap-date-picker should work without warnings of deprecated parts.

## Current Behavior

Getting these following error messages when using <DatePicker /> component:

warning.js:36 Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

warning.js:36 Warning: DatePickerHeader: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.

## Possible Solution

The error messages give some steps to how to avoid getting them. Like using create-react-class and prop-types packages from npm.

## Steps to Reproduce (for bugs)

1. Install  react-bootstrap-date-picker (npm install --save  react-bootstrap-date-picker).
2. Import DatePicker form 'react-bootstrap-date-picker'.
3. Use <DatePicker /> component somewhere in your code.
4. See warning message in developer tools console.

## Your Environment

* Version used: 5.0.1
* Browser Name and version: Chrome: Version 58.0.3029.110 (64-bit)
* Operating System and version (desktop or mobile): Ubuntu xenial 16.04.2 (virtual machine) on Windows 10 host machine

**Comment by nathanvogel** [comment]
Same issue here. 
It seems that the last version available on NPM, 5.0.1, doesn't have the latest changes that I can see on GitHub and still uses React.createClass.

**Comment by jeinz11** [comment]
when will this be available in npm?? is there anyway i can get the latest change?

**Comment by mervynrwtw** [comment]
src/index.jsx#L83 is using PropTypes from React.

**Comment by kunyan** [comment]
@wehriam pls update npm to latest version

**Comment by zerowar** [comment]
@wehriam pls update npm to latest version

**Comment by wehriam** [comment]
Pushed 5.1.0 representing the current master. https://www.npmjs.com/package/react-bootstrap-date-picker

**Comment by nathanvogel** [comment]
Thank you, but as mentioned by mervynrwtw, index.jsx is correctly importing PropTypes from 'prop-types', but still using React.PropTypes instead, which still triggers the warning. See here : https://github.com/pushtell/react-bootstrap-date-picker/blob/master/src/index.jsx#L82

**Comment by wehriam** [comment]
@nathanvogel please consider resolving this issue and creating a pull request.

**Comment by nathanvogel** [comment]
I considered doing so, but I'll need a bit of time since this would be my first time doing a pull request :) I'll try today or tomorrow.

**Comment by IAmSlynchot** [comment]
It looks like #133 addresses the remaining issue with index.jsx, is there any way we can get that merged and released?

**Comment by JonShort** [comment]
I'm keen to see the small fix in [#133](https://github.com/pushtell/react-bootstrap-date-picker/pull/133) go in as the warnings were fixed in [#117](https://github.com/pushtell/react-bootstrap-date-picker/pull/117), but unfortunately regressed in one area with [#123](https://github.com/pushtell/react-bootstrap-date-picker/pull/123/files)

**Comment by JonShort** [comment]
This issue, and #134 are now fixed in master - just need a new minor version pushed to npm. (package.json is ready at version 5.1.1 - current npm version is 5.1.0).

I'm not sure how releasing to npm is being handled at the moment - doesn't seem to be through CI.

**Comment by helcode** [comment]
Use DaemonAlchemist/react-bootstrap-date-picker instead. it supports React16 natively.

**Comment by LennyLip** [comment]
Why is this issue closed?
