### ISSUE TITLE
How to just select year or month?

### ISSUE THREAD

**Issue by BaconZhang** [pushtell/react-bootstrap-date-picker#129]
I have read the docs of [bootstrap-datepicker](https://uxsolutions.github.io/bootstrap-datepicker/?markup=input&format=yyyy&weekStart=&startDate=&endDate=&startView=2&minViewMode=2&maxViewMode=2&todayBtn=false&clearBtn=false&language=en&orientation=auto&multidate=&multidateSeparator=&keyboardNavigation=on&forceParse=on#sandbox) and found that I can just select year or month by setting the Start view, Min view mode and Max view mode. So how could I do the same thing by using react-bootstrap-date-picker? Your timely reply would be much appreciated.

**Comment by SerKnight** [comment]
I don't believe year selection is yet supported.
