### ISSUE TITLE
Rendering and setState issues

### ISSUE THREAD

**Issue by StefanoGitHub** [pushtell/react-bootstrap-date-picker#14]
@wehriam,
I get a rendering/layout issue (see attachment), on both Chrome and Firefox, even with this simple component, similar to the example on the doc:
```
class MyInput extends React.Component {
    constructor(props) {
        super(props);
        this.state =  {
            value: '',
            date: ''
        };
        this.handleChange = this.handleChange.bind(this);
    }
    handleChange(value) {
        // value is an ISO String.
        this.setState({
            value: value,
            date: value.split('T')[0] //just "MM-DD-YYYY"
        });
        console.log(this.state.date);
    }
    render() {
        return <DatePicker value={this.state.value} onChange={this.handleChange}
                           placeholder="MM-DD-YYYY" dateFormat="MM-DD-YYYY"
                           bsSize="small"
        />
    }
}
export default MyInput;
```
Although it might seem to work, despite the rendering problem, I noticed that the value logged and set, in `handleChange()`, as `date` is actually the previously set value and not the current one. 
Let me try to explain better with an example: the first time you select a date on the calendar, let's say `'05-24-2016'`, `this.state.date` is set with (and logged as) an empty string (the initial value). Selecting then another date, e.g. `'05-11-2016'`, it now sets and logs `'05-24-2016'` as `date`. On the following date pick it will set `'05-11-2016'`and so on.

Can you help me with this issues?
I'm using `"react": "^15.0.2", "react-bootstrap": "^0.29.4", "react-dom": "^15.0.2"` and of course the latest `react-bootstrap-date-picker` release 3.0.3
Thanks

![screen shot 2016-05-24 at 10 55 31 pm](https://cloud.githubusercontent.com/assets/12717225/15529720/274ec73c-2204-11e6-8eab-2af70284f3b2.png)

**Comment by wehriam** [comment]
You're logging `this.state.date` in the wrong place.

From the [React documentation](https://facebook.github.io/react/docs/component-api.html):

> `setState()` does not immediately mutate `this.state` but creates a pending state transition. Accessing `this.state` after calling this method can potentially return the existing value.

Also see [this StackOverflow thread](http://stackoverflow.com/questions/30782948/why-calling-react-setstate-method-doesnt-mutate-the-state-immediately) on the subject.

**Comment by StefanoGitHub** [comment]
Thanks @wehriam.
FYI I figure out what was causing the rendering issue: the Bootstrap `Panel` component sets the `color` property (of its children too) to white, so I created this rule to fix it:
`#calendar { color: initial; }`
You might want to consider implementing something like this to avoid such problem in future.
