### ISSUE TITLE
Warning about controlId

### ISSUE THREAD

**Issue by shir** [pushtell/react-bootstrap-date-picker#15]
Has next warning in console
```
Warning: `controlId` is ignored on `<FormControl>` when `id` is specified.
```
My code:
```jsx
            <FormGroup controlId="start_date">
              <Col componentClass={ControlLabel} sm={3}>
                Start date
              </Col>
              <Col sm={9}>
                <DatePicker ref="startDateInput" />
              </Col>
            </FormGroup>
```

I know I may remove `controlId` prop form `FormGroup`, but in this case how I may assign label for input? I want user to be able to click on label to make input in focus.

**Comment by Zephir77167** [comment]
Hello, I'm having the same issue.

**Comment by wehriam** [comment]
Should be resolved in `3.1.0`

**Comment by shir** [comment]
@wehriam thank you!

**Comment by konekoya** [comment]
Sorry to reopening this issue. Run into the same issue and error message from Chrome console
I then found this issue and tried to update the package with NPM.
Unfortunately, NPM cannot update it and lists all of the available versions of this package. The closest version is 2.9x. Anyone can help or explain why? Should I update my NPM or Node.js version? or that's causing by other packages? Thank you!

**Comment by kshitizbuilds** [comment]
Same here,Hope it gets fixed soon

**Comment by JoMaDotio** [comment]
I got the same

**Comment by henrymoore14** [comment]
same here

**Comment by AndrasE** [comment]
Had it today :(
