### ISSUE TITLE
Can't resolve 'create-react-class' 

### ISSUE THREAD

**Issue by walshe** [pushtell/react-bootstrap-date-picker#153]
trying to integrate with https://react-bootstrap.github.io/ but getting issue :

`Can't resolve 'create-react-class' in '/Users/emmett/dev/rc2/frontend/serverless-stack-demo-client/node_modules/react-bootstrap-date-picker/lib`

**Comment by ArmenKesablyan** [comment]
Same issue here as well. Any idea what got updated to break this?

**Comment by sowmitranalla** [comment]
not sure what happened but running `npm install --save create-react-class` fixed the issue about create-react-class. 

now i'm having an issue with undefined values

**Comment by walshe** [comment]
@sowmitranalla  I used what some other guy suggested in an older issue

"react-bootstrap-date-picker": "github:mixxt/react-bootstrap-date-picker",
