### ISSUE TITLE
Min and max date support

### ISSUE THREAD

**Issue by ilmesi** [pushtell/react-bootstrap-date-picker#18]
Nice component! It would be awesome if it have support for min and max date, any way to get that kind of functionality out of the box?

**Comment by wehriam** [comment]
There are no plans for this module to support date ranges.

**Comment by wehriam** [comment]
Sorry, thought you were talking about date ranges. I'll look into min and max support.

**Comment by ilmesi** [comment]
No problem, my scenario involves two datepickers (for check in & check out dates).
Right now I'm using onChange and setState through refs. For instance, using moment js, I would do something like:
var getStateFromMoment = function(date_moment) {
  return {
    value: date_moment.toDate().toISOString(),
    selectedDate: date_moment.toDate(),
    displayDate: date_moment.toDate(),
    inputValue: date_moment.format('DD/MM/YYYY')
  }
}
It would be great to avoid the click event at all.

**Comment by wehriam** [comment]
You may want to take a look at #51

**Comment by docrinehart** [comment]
This appears to have an open PR #80 , and I could really use this functionality. I'd rather update the component than have to switch it out for something else, or roll custom support. Please merge this as soon as possible.
