### ISSUE TITLE
toISOString fails in Safari but not Chrome

### ISSUE THREAD

**Issue by Nopzen** [pushtell/react-bootstrap-date-picker#2]
Hello.

Im currenly faced wit the issue of toISOString fails in a safari browser when i try to run it in the value attribute.

```javascript
<DatePicker value={this.props.todo.deadline} placeholder="Deadline"/>
```

When im mounting the component in Safari i get a error with toISOString. but the error is non replicatateable in Chrome.

Testable ISO String `2016-03-31T10:00:00+0000`

**Comment by Nopzen** [comment]
I found a solution to the issue. 

http://stackoverflow.com/questions/6427204/date-parsing-in-javascript-is-different-between-safari-and-chrome

```javascript
get deadline() {
const deadline = this.props.todo.deadline;
const a = deadline.split(/[^0-9]/);
return new Date(a[0], a[1] - 1, a[2], a[3], a[4], a[5]);
}
```
I will see if i can make a pull request suggestion durring the week, to cater for this Safari issue, with date.

**Comment by wehriam** [comment]
Thanks for posting, although I'm having a hard time understanding the problem. If you have a moment to add a test that illustrates the issue I'll look into it.

**Comment by Nopzen** [comment]
Sure. Ill take a moment to look at it durring the weekend proberly. But mainly the issue is that i have one ISO Standard comming from my backend, and Safari dosent like that ISO format and can therefore not string it.

Ill try to make a test soon as possible.

**Comment by wehriam** [comment]
Unfortunately it looks like the [Date.prototype.toISOString( )](http://www.ecma-international.org/ecma-262/6.0/index.html#sec-date.prototype.toisostring) definition in the [ECMAScript® 2015 Language Specification](http://www.ecma-international.org/ecma-262/6.0/index.html#sec-date.prototype.toisostring) says:

> The time zone is always UTC, denoted by the suffix Z. 

What's generating the ISO string from your backend? For it to work consistently in Javascript you'll probably have to convert it to UTC and use the `Z` suffix rather than a `+0000` offset.

**Comment by Nopzen** [comment]
The backend recives a momentJS ISO String and then converts it to a new ISO String following the ISO 8601 Convension.

So the fix i currently run to make it work with your comp is taking my ISO 8601 String, instantiate a `new Date()` with that ISO String, then i convert it with `.toISOString` and then i make it a string with `.toString`And then passes that string into your component, then it will work. (As in my example number 2).

I have another suggestion for you, would it be possible to pass in a date object instead of a string ? To the `makeDateValues` the reasoning behind this could be that adding support eg. moment to cater for formating the value. 

I could make a pull request for this if you feel interested of updating the makeDateValue, to both support your string and support a date object?

**Comment by wehriam** [comment]
Safari will fail if you pass your date with an offset:

```js
new Date("2016-03-31T10:00:00+0000");
// Returns Invalid Date 
```

**Comment by Nopzen** [comment]
If you pass:
```javascript
moment(deadline).toDate().toString();
```

It works, sorry it was my mistake saying i made a new Date format. I currently use moment to convert it to a string that the Datepicker will understand. Due to the fact Moment will cater for the ISO 8601 Date offset thing.

**Comment by wehriam** [comment]
Would:

```js
moment(deadline).toISOString()
```

Work for you?

As Javascript won't be able to parse `2016-03-31T10:00:00+0000` consistently, I don't see how accepting a `Date` object will help with the problem you're having.

**Comment by wehriam** [comment]
```js
moment("2016-03-31T10:00:00+0000").toISOString()
// returns "2016-03-31T10:00:00.000Z"
```

**Comment by Nopzen** [comment]
```javascript
moment("2016-03-31T10:00:00+0000").toISOString();
```

Passes fine for me yes. thanks for the short cut. Works all good for me now :) Regarding the option for supporting a date object instead, never mind that now :)
