### ISSUE TITLE
Weird input behaviour

### ISSUE THREAD

**Issue by dpwrussell** [pushtell/react-bootstrap-date-picker#21]
I just started using this literally 2 minutes ago and I've found a problem with the input. I can easily replicate it on your example page: http://pushtell.github.io/react-bootstrap-date-picker/

Click anywhere in the text input box one of the dates that are already entered. Delete and or type a number. 

E.g. `06/29/2016`. Say you want to change this to the 7th from the 6th. Place the cursor before the first '6', press delete. Result: `09016`

**Comment by wehriam** [comment]
Thanks for the report. 

I'll try to get to this in the next few days, in the meantime PRs are appreciated!

**Comment by Shivam91** [comment]
@wehriam, my team loves this component and is looking to use it on a project. However this issue is blocking us from recommending it to our demanding users. Would love to know if you have an ETA in mind.
