### ISSUE TITLE
Need the possibility to enable and disable the datepicker based on the application state.

### ISSUE THREAD

**Issue by klausmyrseth** [pushtell/react-bootstrap-date-picker#25]
I miss the feature to render the datepicker and field in a disabled readonly state.

When using in a form, many values will be system managed and read only after these have been created.

It gets quite cluttered when alternating between a normal disabled input field and the datepicker to support this in the front end files. It would be much cleaner having disabled support on the component.

**Comment by rdavidwu** [comment]
I agree this would be useful

**Comment by wehriam** [comment]
Pushed with `3.7.0`
