### ISSUE TITLE
How to handle defaultValue in an update/edit form?

### ISSUE THREAD

**Issue by acomito** [pushtell/react-bootstrap-date-picker#27]
My dates are being stored as ISO strings `"2016-08-18T16:00:00.000Z"`

I'm wondering what I need to do to give a default value to the DatePicker input in my edit/update forms?

For all my other inputs, which are using formsy-react, I'm just passing an event prop and doing `defaultValue={this.props.event.inputValue} `. This doesn't seem to work with the date input when I pass it to the value={this.props.event.date}

Do I have to convert the ISO string back to a number for it to work? This doesn't seem to work either:

`value={Date.parse(this.props.event.date)}`

Because there is no defaultValue prop and only a value prop, do I need to setup local state with an onChange inside my update form to not only give the initial default value but also capture the changed value for updating/editing?

Update:

I guess my dates are stored as ISO strings in the database, but back on the client I'm console logging this from my props:

`Wed Aug 24 2016 12:00:00 GMT-0400 (EDT)`

**Comment by rgstephens** [comment]
I think it would be good to support defaultValue.
