### ISSUE TITLE
IE11 onBlur not supported

### ISSUE THREAD

**Issue by VRedondo** [pushtell/react-bootstrap-date-picker#28]
Hi,
First thanks for such an awesome widget, unfortunately Im having an issue when testing on IE11, it can't support the onBlur event, it says this event is not supported, is there a walk around for this or are you planing to solve this issue in a future version of react-bootstrap-date-picker.

Thanks for your help.

**Comment by VRedondo** [comment]
I see the problem is with this line in the `onChangeDate` method,
`if (this.props.onBlur) {
      this.props.onBlur(new Event("Change Date"));
    }`

seems like IE11 do not support new Event constructor

**Comment by wehriam** [comment]
Resolved in 3.4.0.

**Comment by VRedondo** [comment]
Thanks for this fix @wehriam
