### ISSUE TITLE
Disabling past date

### ISSUE THREAD

**Issue by andreipot** [pushtell/react-bootstrap-date-picker#30]
how can we disable past dates? don't we have minDate prop?

**Comment by wehriam** [comment]
Min and max dates are not currently supported. Closing as a duplicate of #18.

**Comment by andreipot** [comment]
@wehriam  when can we expect that?

**Comment by wehriam** [comment]
This project does not have a roadmap and there is no timeline for this feature. 

Let me know if you would like to discuss professional support options.
