### ISSUE TITLE
Control the clear button visibility

### ISSUE THREAD

**Issue by assaf-farmigo** [pushtell/react-bootstrap-date-picker#35]
Hi, 
Thanks for this great component, is it possible to control the visibility of the clear button.
I have a case which i want to use 2 datePickers and beside them a clear button to clear them both
so i want to remove the clear for the individual component.

**Comment by Nift** [comment]
Hello, 
You imagine this simply being a bool you set on the datepicker?

**Comment by wehriam** [comment]
Pushed with `3.7.0`
