### ISSUE TITLE
January 2017 wrong dates

### ISSUE THREAD

**Issue by ukmarn** [pushtell/react-bootstrap-date-picker#40]
Hey there!
First of all, great job on datepicker, working very well. Just found about it today and perfectly suits my needs. 
But when I implemented and started testing, I found a bug which is that all dates for January 2017 are wrong. Everything else shows correctly.

https://www.dropbox.com/s/ijn027dpe5aikjj/Screenshot%202016-10-13%2016.32.49.png?dl=0

1st of January should be Sunday. 

**UPDATE**
I noticed that this only happens if I have weekStartsOnMonday set to true. If it is else it works good. Also checked your examples page http://pushtell.github.io/react-bootstrap-date-picker/ and bug also exists there when using datepicker which starts with Monday..

**Comment by wehriam** [comment]
Good catch! 

Would you create a test case that illustrates this bug and create a pull request?
