### ISSUE TITLE
onChange(newValue) contains hour even if date format is DD.MM.YYYY

### ISSUE THREAD

**Issue by jarlah** [pushtell/react-bootstrap-date-picker#45]
For ex:

2016-10-31T23:00:00.000Z

Which is completely wrong, because 1) the date picker doesnt support picking time and 2) if the hour is 23 and the date is 31th of October, we get timezone issues with the date picker rendering a displayed value of 01.11.2016.

Can you fix this?

**Comment by wehriam** [comment]
Hi Jarlah,

This repository is community supported.

Please fork the repository, create a test case that in https://github.com/pushtell/react-bootstrap-date-picker/blob/master/test/core.test.jsx that illustrates the issue, and issue a pull request.

**Comment by discordier** [comment]
He means that: `this.props.onChange(selectedDate.toISOString());` is called [here](https://github.com/pushtell/react-bootstrap-date-picker/blob/master/src/index.jsx#L347) but he expected the `onChange` to get called with a value matching what he has defined as `displayValue`

**Comment by wehriam** [comment]
Hi @discordier - if you're also familiar with the issue it would help me resolve the issue sooner if you could create a test case.

**Comment by discordier** [comment]
Not really familiar but read it from his description.

Will give creating a test case a shot though (never done karma tests before).

**Comment by wehriam** [comment]
Happy to help, please don't hesitate to ask if you run into any issues.

**Comment by discordier** [comment]
Please have a look at my implementation idea in #48

**Comment by wehriam** [comment]
Resolved in `3.8.0` by setting all dates to 12:00pm UTC to avoid time zone issues.

**Comment by alex-sherwin** [comment]
Just a note, using 12:00 UTC is common approach, but can lead to issues if you have users in places with +/- greater then 12 hour offsets (New Zealand, American Samoa, etc): https://en.wikipedia.org/wiki/List_of_UTC_time_offsets
