### ISSUE TITLE
onChange should pass through full event object

### ISSUE THREAD

**Issue by rgstephens** [pushtell/react-bootstrap-date-picker#46]
The onChange event from DatePicker should pass on the full event object with the value in event.target.value so that the event can be handled and the value found in the standard location.

**Comment by wehriam** [comment]
This is not possible because both the calendar and text input can change the date value. 

We could emit a synthetic event from the hidden input value as we do on the `onFocus` and `onBlur` handlers, but as it would trail the rendering of the component it would be inaccurate.
