### ISSUE TITLE
Input box allows invalid characters to be passed in

### ISSUE THREAD

**Issue by jemantheiy** [pushtell/react-bootstrap-date-picker#49]
Was able to put a good date in then space then random characters then delete date to get an invalid date w/o receiving an complaint from the component.  

Example:

1.  10/03/2016
2.  10/03/2016 alkdfa
3.  al/kd/fa

The date 10/03/2016 is still captured, but should be validation catching or stopping this kind of input.

**Comment by mvolkmann** [comment]
I can't reproduce this. I'm not able to enter any invalid characters.

**Comment by wehriam** [comment]
I am unable to reproduce `al/kd/fa`.
