### ISSUE TITLE
Usage inside navbar form is broken

### ISSUE THREAD

**Issue by kelkes** [pushtell/react-bootstrap-date-picker#5]
Since the outermost element is a div without any css/styles it breaks the inline style of navbar forms.

I fixed it by adding display:inline-block via css but maybe consider changing it to a span or adding some inline style.

![screen shot 2016-04-18 at 13 52 57](https://cloud.githubusercontent.com/assets/204445/14603244/ee9a4de8-056c-11e6-8287-630439dc6d15.png)

my fix:

`.navbar-form {
    div {
        display: inline-block;
    }
}`

![screen shot 2016-04-18 at 13 54 04](https://cloud.githubusercontent.com/assets/204445/14603270/0954264a-056d-11e6-9326-0efee5140d9f.png)

thanks.

**Comment by wehriam** [comment]
Can you post the JSX of the Navbar?

**Comment by kelkes** [comment]
Of course

`<Navbar fixedTop fluid>
			<Navbar.Header>
				<Navbar.Toggle />
			</Navbar.Header>
			<Navbar.Collapse>
				<Navbar.Form className="navbar-left">
					<form onSubmit={submitHandler}>
						<Button type="submit">xxx</Button>
					</form>
				</Navbar.Form>
				<Navbar.Form className="navbar-left">
					<form>
						<Input type="text" placeholder="Search" />
						{' '}
						<DatePicker />
						{' '}
						<DatePicker />
						{' '}
						<Button type="submit">Submit</Button>
					</form>
				</Navbar.Form>
				<Nav pullRight>
					<Navbar.Text>
						Version: {version}
					</Navbar.Text>
					<NavItem eventKey={4} href="/logout">
						<i className="fa fa-fw fa-sign-out" />
						Logout
					</NavItem>
				</Nav>
			</Navbar.Collapse>
		</Navbar>`

**Comment by wehriam** [comment]
[Release 3.0.0](https://www.npmjs.com/package/react-bootstrap-date-picker) is out and uses `<InputGroup>`, which should resolve this issue.

**Comment by kelkes** [comment]
Thanks!
