### ISSUE TITLE
Popover id is not unique

### ISSUE THREAD

**Issue by jvarho** [pushtell/react-bootstrap-date-picker#57]
If you use the `DatePicker` component twice on a page you end up with HTML elements having duplicate `id`s, because the Popover element has a hardcoded `id`. In addition to being a violation of the spec, this does not play nicely with some other code I'm working with.

I would send a pull request, except I'm not sure what the correct fix is. Changing the value could break someone's code. A new `popoverId` prop that allows overriding it?

**Comment by wehriam** [comment]
I incremented the major revision to avoid problems with existing code and assigned popovers a unique ID.
