### ISSUE TITLE
Datepicker daylight saving creates incorrect date selection

### ISSUE THREAD

**Issue by ptadas** [pushtell/react-bootstrap-date-picker#58]
Say I am on date '2016-11-05' when I select a date that is on or below '2016-10-30' the return value is incorrect. If I am selecting '2016-10-29' I will get '2016-10-28 23:00:00'. I would expect the date picker to be daylight savings time agnostic.

How can I fix this?

**Comment by wehriam** [comment]
Some work has been done in this area with some recent releases. Can you write a test case that illustrates this issue?

**Comment by wehriam** [comment]
I'm going to close this out for now as I believe this is related to an issue that has been resolved in recent versions. Please re-open if this is not the case.
