### ISSUE TITLE
Formatting selected date

### ISSUE THREAD

**Issue by cristian-eriomenco** [pushtell/react-bootstrap-date-picker#59]
Hi, I've been struggling to get a displayed format like '05/Jan/2016'   which would normally be "DD/MMM/YYYY".

The usage is the following:
`<DatePicker value={this.props.dateOpened} onChange={(value) => this.handleChange("dateOpened", value)} type="date" dateFormat="DD/MMM/YYYY"/>`

The result is "YYYY/MM/DD" instead:

![image](https://cloud.githubusercontent.com/assets/7792886/20627555/bc204b10-b318-11e6-8ab8-e355280f258a.png)

Is there a way of achieving the initial intention?

**Comment by wehriam** [comment]
@cristian-eriomenco that formatting option is not currently supported.

**Comment by wehriam** [comment]
You may want try to implement a custom control element using the `customControl` property as illustrated on [the example page](http://pushtell.github.io/react-bootstrap-date-picker/).
