### ISSUE TITLE
Readme Is Misleading for ES5 Projects

### ISSUE THREAD

**Issue by Iancam** [pushtell/react-bootstrap-date-picker#6]
consider including instructions for importing your project to an ES5 project. For ES5 projects, change the first line of usage to 
`var DatePicker = require("react-bootstrap-date-picker").default;`

**Comment by wehriam** [comment]
Ah, sorry about that, I need to build the files with https://github.com/webpack/expose-loader as I have on other projects. 

I'll work on this in the next few days, feel free to create a pull request in the meantime.

**Comment by wehriam** [comment]
[Release 3.0.0](https://www.npmjs.com/package/react-bootstrap-date-picker) is out and should resolve this issue.
