### ISSUE TITLE
Wrong order of components within input group

### ISSUE THREAD

**Issue by Robinfr** [pushtell/react-bootstrap-date-picker#68]
The order of the components within the input group causes the wrong styling. Usually, the Input control goes first which allows the left side of the input to have a cornered border. 

![Normal styling](http://i.imgur.com/EAo0hEU.png)

But in this package the input does not come first, the styling is lost and you end up without the rounded borders.

![Wrong styling](http://i.imgur.com/j0wzO9m.png)

I suggest the input component should go first.

**Comment by Robinfr** [comment]
I've attached a PR to fix this.

**Comment by wehriam** [comment]
Should be resolved with #66
