### ISSUE TITLE
Update react-bootstrap dependent version?

### ISSUE THREAD

**Issue by egeriis** [pushtell/react-bootstrap-date-picker#7]
This error prevents me from installing this lib:

```
npm ERR! peerinvalid The package react-bootstrap@0.29.2 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-bootstrap-date-picker@2.0.0 wants react-bootstrap@^0.28.1
```

Would it be possible to update the dependent version?

**Comment by wehriam** [comment]
I will be able to get to this in the next few days, in the meantime pull requests are appreciated!

**Comment by egeriis** [comment]
I just had a brief look, hoping that it would be easy to resolve. But there has been some API changes, that does not look too easy to resolve. I have some clarifying questions though, which might help guide the way for me to do a PR.

On this line, there's a reference to `document.activeElement`. Where does that come from, and what's the purpose of this check: https://github.com/egeriis/react-bootstrap-date-picker/blob/master/src/index.jsx#L190

Is there a reason, that value is requested through `getValue` here, and not persisted in a state? https://github.com/egeriis/react-bootstrap-date-picker/blob/master/src/index.jsx#L237

This seems a bit hackish, to get a property from the state of another object. As far as I can tell, `react-bootstrap` do provide some callback, to act and set a local state with the necessary properties: https://github.com/egeriis/react-bootstrap-date-picker/blob/master/src/index.jsx#L201

If you can point me in the right direction regarding these questions, I think I'd be dressed to move forward with a PR.

**Comment by wehriam** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Document/activeElement

> Returns the currently focused element, that is, the element that will get keystroke events if the user types any. This attribute is read only.

If I remember correctly that prevents the blur event from being called when the user focuses on the input element.

> Is there a reason, that value is requested through getValue here, and not persisted in a state?

This resolved some state synchronization issues around the handler.

**Comment by brian-kellerheikkila** [comment]
Is there an ETA on this yet?

**Comment by wehriam** [comment]
[Release 3.0.0](https://www.npmjs.com/package/react-bootstrap-date-picker) is out and should resolve this issue.
