### ISSUE TITLE
Testing validations on date picker

### ISSUE THREAD

**Issue by StlthyLee** [pushtell/react-bootstrap-date-picker#74]
I am currently trying to test validations on a form where I am using react-bootstrap-date-picker however I am having a couple of issues. 

In the view I can see that the validations are working correctly, but in the tests something isn't quite right.

I am using `react-addons-test-utils` Simulate like this: 

`Simulate.change(formFields[2], { target: { value: '04/01/2017' } });` in this instance formFields[2] is the date picker however unlike other input fields when I log the value out to the console it is still blank, I was wondering if anyone has a working test example for something like this that could point me in the right direction?

**Comment by wehriam** [comment]
I'm not sure we'll be able to help without a lot more context. Feel free to open another issue if you're still running into this problem.
