### ISSUE TITLE
Warnings in Console

### ISSUE THREAD

**Issue by ljocampo** [pushtell/react-bootstrap-date-picker#8]
I keep getting this warnings in the developer tools console:

![screen shot 2016-05-05 at 11 43 20 am](https://cloud.githubusercontent.com/assets/5980339/15049924/9064cc38-12b6-11e6-8e6a-0a9c7e077d4b.png)

May be I'm missing something?

**Comment by SubatomicHero** [comment]
You're not missing anything. The library needs updating to not use the props in the logs. I get the same errors

**Comment by wehriam** [comment]
[Release 3.0.0](https://www.npmjs.com/package/react-bootstrap-date-picker) is out and uses `<InputGroup>`, which should resolve this issue.
