### ISSUE TITLE
How do I determine which DatePicker with more than one?

### ISSUE THREAD

**Issue by hardija** [pushtell/react-bootstrap-date-picker#94]
If I have more than one DatePicker on a form and want to share a change handler, how do I determine which DatePicker the handleChange call came from?

I don't see where the event object is passed back.

Admittedly, I'm a little new to React, but I think this is a common approach.

**Comment by jvarho** [comment]
There's no way to do that directly. You need a different change handler for each. If you want to use one handleChange method you can do something like (using ES6):

    <DatePicker id={id} {...otherProps} onChange={value => this.handeChange(value, id)} />

**Comment by avremel** [comment]
Isn't this one of the most common use cases, where someone selects a start and end date. Shouldn't there be some way to handle multiple DatePicker's just like input fields in a form?
